# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='Images/NoneU/img.jpg', upload_to='Images/')),
            ],
        ),
    ]
